import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TanStackQueryProvider } from "./provider/tanstack-query";
import { ReactQueryClientProvider } from "@/context/ReactQueryClientProvider";

import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={cn(inter.className, "antialiased min-h-screen")}>
          <TanStackQueryProvider>{children}</TanStackQueryProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
